### ISSUE TITLE
Always add `-Xlambdas=indy` to Kotlin's `freeCompilerArgs`

### ISSUE THREAD

**Issue by CommanderTvis** [mipt-npm/scientifik-gradle-tools#32]
Pros:
* Performance of `invokedynamic` lambdas may be better than of class ones.

Cons:
* `toString` value of lambdas in all the projects may change.

**Comment by altavir** [comment]
Good idea. Since we target JVM 11+.

**Comment by CommanderTvis** [comment]
> Good idea. Since we target JVM 11+.

`lambdas=indy` work correctly even since JDK 1.8

**Comment by altavir** [comment]
Implemented in 0.10.7. Not tested yet.

**Comment by CommanderTvis** [comment]
Doesn't work for some reason.
![image](https://user-images.githubusercontent.com/38042667/143070541-ab3746c9-881b-4bb4-9695-0b2d6e8a0e03.png)
![image](https://user-images.githubusercontent.com/38042667/143070609-bbd2a21b-eea9-4379-b0e5-3186fd362ae7.png)

**Comment by altavir** [comment]
https://github.com/mipt-npm/gradle-tools/blob/59c2a13e4ba33bcad91528048ad1fb518a71e1cc/src/main/kotlin/ru/mipt/npm/gradle/KScienceCommonPlugin.kt#L21
🤷‍♂️

**Comment by CommanderTvis** [comment]
It was a configuration problem.
